#CookBook :: Install filebeat

package "filebeat" do
action :install
end

template "/etc/filebeat/filebeat.yml" do
filebeat.inputs:

# Each - is an input. Most options can be set at the input level, so
# you can use different inputs for various configurations.
# Below are the input specific configurations.

- type: log

  # Change to true to enable this input configuration.
  enabled: true
output.elasticsearch:
  hosts: ["65.0.178.81:9200"]
  index: "test-filebeat"
setup.kibana:
  host: "65.0.178.81/status"
  username: "kibanaadmin"  
  password: "12345"
output.logstash:
  hosts: ["65.0.178.81:5044"]
done

service "filebeat" do
action [:enable, :start]
