#CookBook :: Install filebeat

bash 'filebeat-installation' do
  user 'root'
  curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-6.8.17-linux-x86_64.tar.gz 
  tar xzvf filebeat-6.8.17-linux-x86_64.tar.gz
  cd filebeat-6.8.17-linux-x86_64
end

template "/home/ubuntu/filebeat-6.8.17-linux-x86_64/filebeat.yml" do
filebeat.inputs:
- type: log
  enabled: true
output.elasticsearch:
  hosts: ["65.0.178.81:9200"]
  index: "test-filebeat"
setup.kibana:
  host: "65.0.178.81/status"
  username: "kibanaadmin"  
  password: "12345"
output.logstash:
  hosts: ["65.0.178.81:5044"]
done

service "filebeat" do
action [:enable, :start]
